/**
 * Native Workspace Gallery View Component for DSH `conversation.view` slot.
 * Fully i18n-reactive (Chinese & English) with multi-mode sorting, engine/ratio
 * filtering, grid/list/table view modes, localStorage preference persistence,
 * virtualized rendering, and thumbnail-vs-full image loading.
 */
import { type FC } from 'react';
export interface LocaleService {
    getSnapshot(): {
        active: string;
    };
    subscribe(fn: () => void): () => void;
}
declare const DICT: {
    readonly zh: {
        readonly galleryTitle: "画廊";
        readonly inspiration: "灵感";
        readonly favoritesOnly: "仅收藏";
        readonly manage: "批量管理";
        readonly exitManage: "退出管理";
        readonly selectedCount: "已选 {count} 项";
        readonly selectAll: "全选";
        readonly clearSelect: "清空选择";
        readonly batchDelete: "批量删除";
        readonly confirmBatchDelete: "确定删除选中的 {count} 张图片吗？（不会影响聊天记录）";
        readonly deleteWorkspaceFilesOpt: "同时清理工作区生成文件（不可恢复）";
        readonly workspaceOnly: "当前工作区";
        readonly workspaceAll: "所有工作区";
        readonly workspaceUnavailable: "当前工作区（需要会话范围）";
        readonly regenerate: "重新生成";
        readonly regenerating: "生成中…";
        readonly regenerateSuccess: "已生成新图片";
        readonly regenerateFailed: "重新生成失败";
        readonly usePrompt: "使用 Prompt";
        readonly totalCount: "共 {count} 张生成图片";
        readonly searchPlaceholder: "搜索 Prompt 关键词…";
        readonly clearSearch: "清空搜索";
        readonly engineAll: "全部";
        readonly filterGPT: "GPT Image 2";
        readonly filterGemini: "Gemini Image";
        readonly filterUnknown: "未知引擎";
        readonly ratioFilter: "比例";
        readonly ratioAll: "全部比例";
        readonly sortBy: "排序";
        readonly sortTimeDesc: "最新生成";
        readonly sortTimeAsc: "最早生成";
        readonly sortPromptAsc: "Prompt A→Z";
        readonly sortPromptDesc: "Prompt Z→A";
        readonly sortSizeDesc: "文件从大到小";
        readonly viewGrid: "网格视图";
        readonly viewList: "列表视图";
        readonly viewTable: "表格视图";
        readonly emptyTitle: "暂无生图记录";
        readonly emptyDesc: "在对话中让 Agent 生图后，生成的图片会自动收录到这里。";
        readonly noMatchTitle: "未找到匹配结果";
        readonly noMatchDesc: "尝试更换搜索关键词或选择其他引擎。";
        readonly copiedPrompt: "已复制 Prompt";
        readonly copiedImage: "已复制图片";
        readonly copyFailed: "复制失败";
        readonly favoriteAdded: "已添加到收藏";
        readonly favoriteRemoved: "已取消收藏";
        readonly preview: "查看大图";
        readonly download: "下载图片";
        readonly copyImg: "复制图片";
        readonly copyPpt: "复制 Prompt";
        readonly delete: "从画廊删除";
        readonly confirmDelete: "确定要从画廊中删除这张图片吗？（不会影响原聊天记录）";
        readonly deleted: "已从画廊删除";
        readonly deleteFailed: "工作区文件清理失败，未删除画廊记录";
        readonly confirmDeleteWorkspace: "同时删除这张图片的工作区文件吗？此操作不可恢复。";
        readonly prompt: "Prompt";
        readonly close: "关闭 (Esc)";
        readonly prev: "上一张";
        readonly next: "下一张";
        readonly colPrompt: "Prompt";
        readonly colEngine: "引擎";
        readonly colResolution: "分辨率";
        readonly colSize: "文件大小";
        readonly colTime: "生成时间";
        readonly colActions: "操作";
    };
    readonly en: {
        readonly galleryTitle: "Gallery";
        readonly inspiration: "Inspiration";
        readonly favoritesOnly: "Favorites";
        readonly manage: "Batch manage";
        readonly exitManage: "Done";
        readonly selectedCount: "{count} selected";
        readonly selectAll: "Select all";
        readonly clearSelect: "Clear selection";
        readonly batchDelete: "Delete selected";
        readonly confirmBatchDelete: "Delete {count} selected images? (Chat history is not affected)";
        readonly deleteWorkspaceFilesOpt: "Also delete generated workspace files (cannot be undone)";
        readonly workspaceOnly: "Current workspace";
        readonly workspaceAll: "All workspaces";
        readonly workspaceUnavailable: "Current workspace (session scope required)";
        readonly regenerate: "Regenerate";
        readonly regenerating: "Generating…";
        readonly regenerateSuccess: "New image generated";
        readonly regenerateFailed: "Regeneration failed";
        readonly usePrompt: "Use prompt";
        readonly totalCount: "{count} images total";
        readonly searchPlaceholder: "Search prompt keywords…";
        readonly clearSearch: "Clear search";
        readonly engineAll: "All";
        readonly filterGPT: "GPT Image 2";
        readonly filterGemini: "Gemini Image";
        readonly filterUnknown: "Unknown engine";
        readonly ratioFilter: "Aspect ratio";
        readonly ratioAll: "All ratios";
        readonly sortBy: "Sort";
        readonly sortTimeDesc: "Newest first";
        readonly sortTimeAsc: "Oldest first";
        readonly sortPromptAsc: "Prompt A→Z";
        readonly sortPromptDesc: "Prompt Z→A";
        readonly sortSizeDesc: "Largest file";
        readonly viewGrid: "Grid view";
        readonly viewList: "List view";
        readonly viewTable: "Table view";
        readonly emptyTitle: "No images generated yet";
        readonly emptyDesc: "Images generated during conversations will automatically appear here.";
        readonly noMatchTitle: "No matching images";
        readonly noMatchDesc: "Try a different search keyword or engine filter.";
        readonly copiedPrompt: "Prompt copied";
        readonly copiedImage: "Image copied";
        readonly copyFailed: "Copy failed";
        readonly favoriteAdded: "Added to favorites";
        readonly favoriteRemoved: "Removed from favorites";
        readonly preview: "Full Preview";
        readonly download: "Download";
        readonly copyImg: "Copy Image";
        readonly copyPpt: "Copy Prompt";
        readonly delete: "Delete from gallery";
        readonly confirmDelete: "Are you sure you want to remove this image from the gallery? (Chat history will not be affected)";
        readonly deleted: "Deleted from gallery";
        readonly deleteFailed: "Workspace cleanup failed; gallery record was kept";
        readonly confirmDeleteWorkspace: "Also delete this image's workspace file? This cannot be undone.";
        readonly prompt: "Prompt";
        readonly close: "Close (Esc)";
        readonly prev: "Previous";
        readonly next: "Next";
        readonly colPrompt: "Prompt";
        readonly colEngine: "Engine / Model";
        readonly colResolution: "Resolution";
        readonly colSize: "Size";
        readonly colTime: "Created";
        readonly colActions: "Actions";
    };
};
export type DictKey = keyof typeof DICT.zh;
export type GalleryTab = 'gallery' | 'inspiration';
export interface GalleryViewTabProps {
    locale?: LocaleService | undefined;
    scope?: {
        sessionId: string;
        cwd?: string | undefined;
        repoRoot?: string | undefined;
    } | undefined;
    visible?: boolean | undefined;
}
export declare const GalleryViewTab: FC<GalleryViewTabProps>;
export declare function copyImageBlob(blob: Blob): Promise<boolean>;
export {};
