/**
 * In-memory mirror of the workbench infinite canvas.
 *
 * The tldraw canvas lives in the browser; the conversation agent lives in the
 * host process. Browser instances push compact `CanvasStatePush` snapshots
 * through the canvas-state route, and this mirror is the host-side truth the
 * system-prompt digest, the canvas_state / view_canvas tools, and the
 * edit_image `canvas_selection` source all read from. Nothing here is
 * persisted: the mirror dies with the host process, matching the canvas's
 * own session-scratch semantics.
 */
import type { ImageMediaType } from '@deepseek-ai/dsh-attachment'
import type { CanvasNodeSummary, CanvasStatePush } from './shared.js'

/**
 * Decoded selection screenshot held in memory only. Nothing touches the
 * durable attachment store until a tool actually consumes it: most
 * screenshots are replaced within seconds (selection changed) or die with
 * the canvas (closed), and the immutable content-addressed store has no
 * deletion — persisting them eagerly would leak disk forever.
 */
export interface CanvasSelectionImage {
  data: Uint8Array
  mediaType: ImageMediaType
}

/** Server-side view of one client push after validation. */
export interface CanvasMirrorEntry {
  clientInstance: string
  connected: true
  nodeCount: number
  nodes: readonly CanvasNodeSummary[]
  selectionCount: number
  selectionKinds: readonly string[]
  /** Capped identity list of the selected shapes (name, attachment id, ...). */
  selectionItems: readonly CanvasNodeSummary[]
  /**
   * Identity-bearing selection signature (count + kinds + item identities).
   * Two selections of different shapes never share it, so a stale screenshot
   * is never kept across a selection swap — even when count and kinds match.
   */
  selectionSignature: string
  /** In-memory screenshot of the current selection, when one was pushed. */
  selectionImage?: CanvasSelectionImage
  selectionStatus?: CanvasStatePush['selectionStatus']
  selectionError?: string
  /** Mirror receive time, used for the digest's "updated N ago" line. */
  receivedAt: number
  /** Monotonic apply counter; `latest()` prefers the most recently applied instance. */
  seq: number
  updatedAt: number
}

/** How many node lines the digest lists before collapsing to "+N more". */
const DIGEST_NODE_LIMIT = 24
/** How many selected shapes the digest itemizes before collapsing. */
const DIGEST_SELECTION_LIMIT = 12

/**
 * Identity-bearing selection signature. Count and kinds alone would make
 * "1 selected image" of the lion and of the monster indistinguishable; the
 * item summaries (name, attachment id, dimensions, text) keep them apart.
 */
function signatureOf(count: number, kinds: readonly string[], items: readonly CanvasNodeSummary[]): string {
  return JSON.stringify([count, kinds, items])
}

function describeNode(node: CanvasNodeSummary): string {
  switch (node.kind) {
    case 'image': {
      const size = typeof node.width === 'number' && typeof node.height === 'number' ? `${node.width}x${node.height}` : undefined
      const name = typeof node.name === 'string' && node.name.length > 0 ? `"${node.name}"` : undefined
      const attachment = typeof node.attachmentId === 'string' ? `conversation attachment ${node.attachmentId}` : undefined
      // Generation provenance: lets "regenerate this" / "vary this" reuse the
      // original prompt and model instead of guessing from pixels alone.
      const generatedBy = typeof node.provider === 'string' && node.provider.length > 0
        ? `generated by ${node.provider}${typeof node.model === 'string' && node.model.length > 0 ? `/${node.model}` : ''}`
        : undefined
      const prompt = typeof node.prompt === 'string' && node.prompt.length > 0 ? `prompt "${node.prompt}"` : undefined
      return ['image', size, name, attachment, generatedBy, prompt].filter(part => part !== undefined).join(' ')
    }
    case 'draw':
      return 'draw (freehand stroke)'
    case 'text':
    case 'note': {
      const preview = typeof node.text === 'string' && node.text.length > 0 ? `"${node.text}"` : '(empty)'
      return `${node.kind} ${preview}`
    }
    case 'geo':
      return typeof node.name === 'string' && node.name.length > 0 ? `shape ${node.name}` : 'shape'
    default:
      return node.kind
  }
}

/** The most recently applied connected entry, or undefined when none is connected. */
function freshestEntry(entries: Iterable<CanvasMirrorEntry>): CanvasMirrorEntry | undefined {
  let latest: CanvasMirrorEntry | undefined
  for (const entry of entries) {
    if (latest === undefined || entry.seq > latest.seq) latest = entry
  }
  return latest
}

/**
 * Host-side mirror of every currently connected workbench canvas.
 *
 * One instance is shared by the canvas-state route, the canvas tools, and the
 * system-prompt context registration. More than one canvas can be mounted at
 * once (right-sidebar studio tab, conversation gallery tab); each instance
 * pushes under its own `clientInstance` id and `latest()` reads the freshest.
 */
export class CanvasMirror {
  private readonly entries = new Map<string, CanvasMirrorEntry>()
  private readonly sequences = new Map<string, { value: number; receivedAt: number }>()
  private nextSeq = 0

  /**
   * Apply one validated push. A disconnect removes the instance; an unchanged
   * selection keeps the previously received screenshot bytes so the model can
   * still view them while unrelated canvas edits keep flowing in.
   */
  apply(push: CanvasStatePush, selectionImage?: CanvasSelectionImage): void {
    // Keep short-lived disconnect tombstones so an older in-flight upload
    // cannot resurrect a closed canvas or replace a newer selection.
    for (const [id, item] of this.sequences) {
      if (Date.now() - item.receivedAt > 5 * 60_000) this.sequences.delete(id)
    }
    if (push.sequence !== undefined) {
      if (push.sequence <= (this.sequences.get(push.clientInstance)?.value ?? -1)) return
      this.sequences.set(push.clientInstance, { value: push.sequence, receivedAt: Date.now() })
    }
    if (!push.connected) {
      this.entries.delete(push.clientInstance)
      return
    }
    const previous = this.entries.get(push.clientInstance)
    const selectionCount = push.selection?.count ?? 0
    const selectionKinds = [...(push.selection?.kinds ?? [])]
    const selectionItems = [...(push.selection?.items ?? [])]
    const selectionSignature = push.selectionRevision === undefined
      ? signatureOf(selectionCount, selectionKinds, selectionItems)
      : JSON.stringify([push.selectionRevision, selectionCount])
    const keepImage = push.selectionStatus !== 'preparing' && previous !== undefined && previous.selectionSignature === selectionSignature
      ? previous.selectionImage
      : undefined
    this.entries.set(push.clientInstance, {
      clientInstance: push.clientInstance,
      connected: true,
      nodeCount: push.nodeCount,
      nodes: [...(push.nodes ?? [])],
      selectionCount,
      selectionKinds,
      selectionItems,
      selectionSignature,
      ...(push.selectionStatus === undefined ? {} : { selectionStatus: push.selectionStatus }),
      ...(push.selectionError === undefined ? {} : { selectionError: push.selectionError }),
      ...(selectionImage !== undefined
        ? { selectionImage }
        : keepImage !== undefined ? { selectionImage: keepImage } : {}),
      receivedAt: Date.now(),
      seq: ++this.nextSeq,
      updatedAt: push.updatedAt,
    })
  }

  /** The freshest connected canvas entry, or undefined. */
  latest(): CanvasMirrorEntry | undefined {
    return freshestEntry(this.entries.values())
  }

  /** The in-memory selection screenshot of the freshest canvas, if present. */
  latestSelectionImage(): CanvasSelectionImage | undefined {
    const entry = this.latest()
    return entry?.selectionImage
  }

  /** Whether any canvas instance is currently connected. */
  connected(): boolean {
    return this.latest() !== undefined
  }

  /**
   * Compact one-screen digest of the canvas for the system prompt and tools.
   * Evaluated per call so the "updated N ago" line stays current between pushes.
   */
  digest(now: number = Date.now()): string {
    const entry = this.latest()
    if (entry === undefined) {
      return [
        'Image-gen workbench canvas: not connected.',
        'No image-gen workbench infinite canvas is open right now. If the user refers to a canvas, drawings, or a sketch, ask them to open the image-gen workbench (gallery tab or right-sidebar studio tab) and switch it to the infinite canvas view.',
      ].join(' ')
    }
    const lines: string[] = []
    const kindCounts = new Map<string, number>()
    for (const node of entry.nodes) kindCounts.set(node.kind, (kindCounts.get(node.kind) ?? 0) + 1)
    const unlisted = Math.max(0, entry.nodeCount - entry.nodes.length)
    const shapeTotal = `${entry.nodeCount} shape${entry.nodeCount === 1 ? '' : 's'}`
    const breakdown = [...kindCounts.entries()].map(([kind, count]) => `${count} ${kind}${count === 1 ? '' : 's'}`).join(', ')
    const age = Math.max(0, Math.round((now - entry.receivedAt) / 1000))
    const ageText = age < 5 ? 'just now' : age < 90 ? `${age}s ago` : `${Math.round(age / 60)}min ago`
    lines.push(`Image-gen workbench canvas: ${shapeTotal}${breakdown.length > 0 ? ` (${breakdown})` : ''}, updated ${ageText}.`)
    for (const node of entry.nodes.slice(0, DIGEST_NODE_LIMIT)) {
      lines.push(`- ${describeNode(node)}`)
    }
    if (entry.nodes.length > DIGEST_NODE_LIMIT) {
      lines.push(`- ... ${entry.nodes.length - DIGEST_NODE_LIMIT} more shapes omitted`)
    }
    if (unlisted > 0) {
      lines.push(`- (${unlisted} further shapes not itemized)`)
    }
    if (entry.selectionCount === 0) {
      lines.push('Selection: none. Ask the user to select shapes on the canvas when they want you to work on something specific.')
    } else {
      const kinds = entry.selectionKinds.length > 0 ? ` (${entry.selectionKinds.join(', ')})` : ''
      lines.push(`Selection: ${entry.selectionCount} shape${entry.selectionCount === 1 ? '' : 's'}${kinds}.`)
      // Itemize the selection: without this the model cannot tell WHICH shapes
      // are selected when several share a kind (e.g. two 1024x1024 images).
      for (const item of entry.selectionItems.slice(0, DIGEST_SELECTION_LIMIT)) {
        lines.push(`- selected: ${describeNode(item)}`)
      }
      if (entry.selectionItems.length > DIGEST_SELECTION_LIMIT) {
        lines.push(`- ... ${entry.selectionItems.length - DIGEST_SELECTION_LIMIT} more selected shapes omitted`)
      }
      const unlistedSelection = Math.max(0, entry.selectionCount - entry.selectionItems.length)
      if (unlistedSelection > 0) {
        lines.push(`- (${unlistedSelection} further selected shapes not itemized)`)
      }
      const screenshot = entry.selectionImage !== undefined
        ? 'A screenshot of the selection is available; call view_canvas to see it. edit_image with source=canvas_selection uses separately synchronized originals, including images from earlier conversations and imports, plus the screenshot for mixed selections. Provider reference-count limits still apply.'
        : entry.selectionError !== undefined
          ? `Selection synchronization failed: ${entry.selectionError}. Ask the user to retry using the canvas status bar. Do not claim that image-only selections are invisible or suggest adding a stroke.`
          : 'The selection preview and original images are being prepared. Wait for the canvas status bar to report ready, then retry.'
      lines.push(screenshot)
      if (entry.selectionImage !== undefined && entry.selectionError !== undefined) lines.push(`The preview is available, but original synchronization failed: ${entry.selectionError}. Editing must not silently omit these references.`)
    }
    return lines.join('\n')
  }
}
